spring:
  datasource:
    url: jdbc:mysql://localhost:3306/year_project?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root2000
  jpa:
    hibernate:
      ddl-auto: update
